### ISSUE TITLE
[1.7.10] Minechem is in an Errored Mod State - V2

### ISSUE THREAD

**Issue by Wealthyturtle** [iopleke/Minechem#842]
@jakimfett Re-read the guidelines, hope this is what you needed:

- It can be reproduced with other Mods. Try any Minechem Release at CurseForge, with a Better Builders' Wands Release at CurseForge (I used the Latest Versions of both Mods (Minechem: https://minecraft.curseforge.com/projects/minechem/files/2251057, Better Builders' Wands: https://minecraft.curseforge.com/projects/better-builders-wands/files/2356820)).
 
- It can't be reproduced with just Minechem. The only Mod I'm aware of that causes this crash is Better Builders' Wands. 
(Do Note: I can't compile Minechem with the source code you provided (Minechem Build Version 1.7.10-5.0.5.394 due to Eclipse (My Java compiler) complaining that you're using "fluidID", a un-resolved variable that is being used, and the fact that Minechem is calling in code from Java 7, which doesn't work for me since I'm running Java 8. Also, I'm using Forge-1.7.10-10.13.4.1614 if it matters)).

- I'm a Modpack Author myself, you can check out the Modpack here: Universal: Interdimensional Escape. The mod list is provided in the Modpack's Project Description Page. And yes, I have identified the mod - Better Builders' Wands. When I removed it from the mods folder, the game started with no problems, and the game was not in a frozen data state.

- Yes, it is something broken if you consider that it's causing the game to be in a frozen data state for some reason, but when you remove Better Builders' Wands, it somehow works. I personally want both mods to be used in my Modpack, without having to remove either from my mod list.

- Not sure if this is a bug on Better Builders' Wands, or if it's a bug on Minechem, but either way, it should be resolved.

- I used the latest version of Minechem, which is available on Minechem's CurseForge Page (https://minecraft.curseforge.com/projects/minechem/files/2251057). Like I said earlier, I can't use your Minechem Build Version 1.7.10-5.0.5.394 due to Eclipse (My Java compiler) complaining that you're using "fluidID", a un-resolved variable that is being used, and the fact that Minechem is calling in code from Java 7, which doesn't work for me since I'm running Java 8. So I can't determine whether or not it this is fixed in Minechem Build Version 1.7.10-5.0.5.394.

- Reproduction steps are stated above.

- Version used for testing is stated above as well.

- There was no crash; it just caused the game to be in a frozen data state; meaning you can start up the game, but can't log into servers or singleplayer worlds.

- I followed everything from https://github.com/iopleke/Minechem/wiki/Bug-Reporting-Guidelines, all in point form and all organized according to the order that was put in that wiki page.

- I also didn't do "Capitalization on every word" unless on terms such as "Minechem / Better Builders' Wands / Java (Names)" or "Mods / Modpacks (Specific keywords).

Additional Stuff:

Information on the "fluidID" Errors:
![untitled](https://cloud.githubusercontent.com/assets/19924575/21961179/b74e993c-db3d-11e6-901a-77fa27a4c8a3.png)

Frozen data state information:
[http://pastebin.com/CYKEEB2T](http://pastebin.com/CYKEEB2T)

For Reference: 
https://github.com/iopleke/Minechem/issues/841
https://github.com/iopleke/Minechem/issues/808
https://github.com/portablejim/BetterBuildersWands/issues/4

**Comment by Raxmo** [comment]
hmmm.... I am also having the same issue, and I to want better builder's wand AND minechem. At least now I know where the issue resides. Seems like I'll have to choose one or the other until this issue is resolved. I at least have the luxury of axing better builder's wand I think... I wish you luck on this, it is an odd issue.

**Comment by janagyjr** [comment]
I'm having the same issue and I'm using the latest available from CurseForge.

**Comment by Blue64** [comment]
The fix for the `FluidID` issue is to implement the `Forge` Workspace, that's what is needed to resolve the `FluidID val` correctly, make sure you are using the `1.7.10 Eclipse Build`, as once `Forge` moved out of `1.7.10` they changed a lot of stuff for their `Eclipse Formatting`.

my [Minechem](https://minecraft.curseforge.com/projects/minechem/files?filter-game-version=2020709689%3A4449) version is:
[`Minechem-1.7.10-5.0.5.406`](https://minecraft.curseforge.com/projects/minechem/files/2251057)
which is the current latest release
I had this running correctly in Single Player just the other day, no Data Freeze, I even recall [I burned to death in Lava](https://www.youtube.com/watch?v=TjeuUfJrGBY&index=3&list=PLVt4xuErUQB6OIm1Umg-j13GTL8DYfn8g&t=38m57s) (I too am building a [ModPack](https://github.com/Blue64/Infernal_Rift))

my Computer Specs are:
```
-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_73, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 69093088 bytes (65 MB) / 159133696 bytes (151 MB) up to 2141913088 bytes (2042 MB)
	JVM Flags: 42 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+AggressiveHeap -XX:+AggressiveOpts -XX:+AlwaysPreTouch -XX:+CMSScavengeBeforeRemark -XX:+ExplicitGCInvokesConcurrent -XX:+ParallelRefProcEnabled -XX:+ScavengeBeforeFullGC -XX:+UseCodeCacheFlushing -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseStringDeduplication -XX:-DisableExplicitGC -XX:-UseAdaptiveSizePolicy -XX:-UseCompressedOops -XX:-UseG1GC -XX:-UseParallelGC -XX:-UseSerialGC -XX:ReservedCodeCacheSize=128M -XX:InitialHeapSize=256M -XX:MaxNewSize=32M -XX:NewSize=8M -Xms64M -Xmx2048M -Xss2M -XX:CMSExpAvgFactor=10 -XX:CMSTriggerRatio=95 -XX:CodeCacheMinimumFreeSpace=64M -XX:ConcGCThreads=1 -XX:G1HeapRegionSize=16M -XX:G1ReservePercent=5 -XX:InitialCodeCacheSize=128M -XX:InitialSurvivorRatio=4 -XX:InitiatingHeapOccupancyPercent=75 -XX:MaxGCPauseMillis=250 -XX:MaxHeapFreeRatio=50 -XX:MaxTenuringThreshold=8 -XX:MinHeapFreeRatio=5 -XX:ParallelGCThreads=1 -XX:StringDeduplicationAgeThreshold=2 -XX:SurvivorRatio=4 -XX:TargetSurvivorRatio=50
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.4.12874 Compatibility Profile Context 14.100.0.0' Renderer: 'AMD Radeon HD 6310 Graphics'
```

**Comment by Wealthyturtle** [comment]
@Blue64 Again, do you have Better Builders' Wands in your Modpack, and how do you Create the "1.7.10 Eclipse Build" to implement the "Forge Workspace"? I did "gradlew eclipse" is that not enough?

**Comment by Wealthyturtle** [comment]
Fixed! I'm releasing a mod to fix this issue, once it is released it will be placed here: https://minecraft.curseforge.com/projects/minechem-1-7-10-reworked
@Blue64 @Raxmo @janagyjr 

@jakimfett @way2muchnoise 
Hope you guys don't mind too much.

**Comment by Wealthyturtle** [comment]
https://github.com/Wealthyturtle/Minechem-1.7.10-Reworked Actually.

**Comment by Jonius7** [comment]
@Wealthyturtle 
> @Blue64 Again, do you have Better Builders' Wands in your Modpack, and how do you Create the "1.7.10 Eclipse Build" to implement the "Forge Workspace"? I did "gradlew eclipse" is that not enough?

`gradlew setupDecompWorkspace` before `gradlew eclipse`

I tried out your Minechem-1.7.10-Reworked, but in reality I just wanted Vanilla Minechem with the BetterBuildersWands fix.

Update: so I was able to get BetterBuildersWands to work with a build of Minechem. **With the element Fluid buckets.**

Spent a long while trying to get the build from https://github.com/iopleke/Minechem to compile. `build.gradle` files were well outdated. When I finally got it working, I realised that `1.7.10-v6` was set as the default branch and it was working off that. It was missing a whole bunch of folders and added Fontbox as a module dependency. It also doesn't have the element buckets or Fluid items. 
The folder structure didn't match the Minechem-1.7.10-5.0.5.406.jar that is available on CurseForge. So, I guess `master` is the branch I'm looking for. Compiled off that with the `build.gradle` and `build.properties` I just updated, and all seems to be working. 

(Only thing is it's built with "ManuallyBuilt" in the filename, and the version number is showing 6.0.@Revis@. Minor things, I'll have a 2nd look at the build.gradle in master, rather than overwriting it).

**Comment by jakimfett** [comment]
Oi, @Wealthyturtle, in case there was any confusion, I'm completely on board with any updates you want to make.

I'm (hoping) that the holidays will give me enough time to set up a few people as having developer privileges on the minecraft stuffs here, so if you or @Jonius7 want to be part of that, just say the word.

**Comment by Jonius7** [comment]
> I'm (hoping) that the holidays will give me enough time to set up a few people as having developer privileges on the minecraft stuffs here, so if you or @Jonius7 want to be part of that, just say the word.

Ah I completely missed this. I think at the time I wasn't really up to the task of being a mod dev, I'm still not very good, but I have learnt stuff fixing other 1.7.10 mods to get them to work in my modpack.

So, sure. I would also like to get the build that's working with BetterBuildersWands up on CurseForge.
